config/routes.rb
Photobooth::Application.routes.draw do
  root :to => "photo_sessions#index"
  resources :photo_sessions do
    get "/print" => "photo_sessions#print"
  end
end

app/models/photo_session.rb
class PhotoSession < ActiveRecord::Base
  has_attached_file :photo_1
  has_attached_file :photo_2
  has_attached_file :photo_3
  validates_attachment_content_type :photo_1, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo_2, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo_3, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_sessions_controller.rb
class PhotoSessionsController < ApplicationController
  def index
    @photo_sessions = PhotoSession.order(:created_at => :desc)
  end

  def create
    @photo_session = PhotoSession.new(photo_session_params)
    if @photo_session.save
      redirect_to photo_session_print_path(@photo_session)
    else
      render :json => {:success => false}
    end
  end

  def show
    @photo_session = PhotoSession.find(params[:id])

    html = render_to_string
    save_path = "#{Rails.root}/tmp/photo_session_#{params[:id]}.html"
    pdf_save_path = "#{Rails.root}/tmp/photo_session_#{params[:id]}.pdf"
    File.open(save_path, 'wb') do |file|
        file << html
    end
    `wkhtmltopdf --page-width 5in --page-height 7in --margin-left 0 --margin-right 0 --margin-top 0 --margin-bottom 0 #{save_path} #{pdf_save_path}`
    send_file(pdf_save_path, :filename => "photo_session_#{@photo_session.id}.pdf", :disposition => 'inline', :type => "application/pdf")
  end

  def destroy
    @photo_session = PhotoSession.find(params[:id])
    @photo_session.destroy
    redirect_to photo_sessions_path
  end

  def print
    @photo_session = PhotoSession.find(params[:photo_session_id])

    html = render_to_string
    save_path = "#{Rails.root}/tmp/photo_session_#{params[:photo_session_id]}.html"
    pdf_save_path = "#{Rails.root}/tmp/photo_session_#{params[:photo_session_id]}.pdf"
    File.open(save_path, 'wb') do |file|
        file << html
    end
    `wkhtmltopdf --page-width 5in --page-height 7in --margin-left 0 --margin-right 0 --margin-top 0 --margin-bottom 0 #{save_path} #{pdf_save_path}`
    `lpr #{pdf_save_path}`
    redirect_to photo_sessions_path
  end
  private
  def photo_session_params
    params.require(:photo_session).permit(:email_address, :photo_1, :photo_2, :photo_3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_sessions_helper.rb
module PhotoSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photobooth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdf/pdf_mailer.html.haml
Here are your pictures!

app/views/photo_sessions/index.html.haml
:css
  img {
    width: 100px;
    height: 50px;
  }
%table
  %thead
    %tr
      %th Created At
      %th Pictures
      %th Email
      %th Actions
  %tbody 
    - @photo_sessions.each do |photo_session|
      %tr
        %td=photo_session.created_at
        %td
          = image_tag photo_session.photo_1.url
        %td= photo_session.email_address
        %td
          =link_to "Show", photo_session_path(photo_session), class: "btn"
          =link_to "Print", photo_session_print_path(photo_session), class: "btn"
          =link_to "Delete", photo_session_path(photo_session),class: "btn", method: :delete

app/views/photo_sessions/print.html.haml
:css
  @font-face {
      font-family: 'snell_roundhandregular';
      src: url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.eot');
      src: url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.eot?#iefix') format('embedded-opentype'),
        url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.woff') format('woff'),
          url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.ttf') format('truetype'),
            url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.svg#snell_roundhandregular') format('svg');
      font-weight: normal;
      font-style: normal;

  }

  body {
    width: 5in;
    height: 7in;
  }
  
  img {
     -webkit-transform: scaleY(-1);
     width: 5in;
     float: left;
     margin-bottom: 5px;
     -webkit-box-shadow: 1px -3px 5px 0px rgba(0,0,0,0.75);
  }
  
  span {
    position: absolute;
    top: 425px;
    left: 195px;
    width: 700px;
    -webkit-transform: rotate(90deg);
    font-family: 'snell_roundhandregular';
    font-size: 30pt;
    font-weight: bold;
  }
%span Candace & Andrew February 22, 2014
=image_tag @photo_session.photo_1.path
=image_tag @photo_session.photo_2.path
=image_tag @photo_session.photo_3.path

app/views/photo_sessions/show.html.haml
:css
  @font-face {
      font-family: 'snell_roundhandregular';
      src: url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.eot');
      src: url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.eot?#iefix') format('embedded-opentype'),
        url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.woff') format('woff'),
          url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.ttf') format('truetype'),
            url('#{Rails.root}/public/ufonts.com_snell_roundhand_script_1_-webfont.svg#snell_roundhandregular') format('svg');
      font-weight: normal;
      font-style: normal;

  }

  body {
    width: 5in;
    height: 7in;
  }
  
  img {
     -webkit-transform: scaleY(-1);
     width: 5in;
     float: left;
     margin-bottom: 5px;
  }
  
  span {
    position: absolute;
    top: 425px;
    left: 195px;
    width: 700px;
    -webkit-transform: rotate(90deg);
    font-family: 'snell_roundhandregular';
    font-size: 30pt;
    font-weight: bold;
  }
%span Candace & Andrew February 22, 2014
=image_tag @photo_session.photo_1.path
=image_tag @photo_session.photo_2.path
=image_tag @photo_session.photo_3.path